# Generated by Django 4.2.4 on 2023-08-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
                ('board_name', models.CharField(max_length=20, verbose_name='board name')),
                ('is_secret', models.BooleanField(default=False, verbose_name='is secret')),
            ],
        ),
    ]
