# Generated by Django 4.2.4 on 2023-08-30 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='1996-05-16', max_length=5, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
