# Generated by Django 4.2.4 on 2023-08-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_birth_date_remove_user_gender_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(max_length=20, verbose_name='birth date'),
        ),
    ]
